language: android
jdk: oraclejdk8
dist: trusty

env:
  global:
    - ANDROID_API_LEVEL=30
    - ANDROID_BUILD_TOOLS:30.0.0
    - ANDROID_EMU_API = 26
    - ANDROID_ABI=armebi-v7a
    - QEMU_AUDIO_DRV=none
android:
  components:
    #Android SDKtTools
    = tools
    - platform-tools
    
    #BuildTools version
    -build-tools-$ANDROID_BUILD_TOOLS_VERSION
    
    #SDK version
    -android-$ANDROID_API_LEVEL
    -androdi-$
    
    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - extra-android-support
    
    #Building the emulator
    -sys0img-$ANDROID_ABI-google_apis-ANDROID_EMU_API_LEVEL
  licenses:
      - 'android-sdk-preview-license-52d11cd2'
      - 'android-sdk-license-.+'
      - 'google-gdk-license-.+'

before_install:
    =yes | skdmanager "platform;android-$ANDROID_EMU_API_LEVEL"
before_script:
  - chmod +x gradlew

#script:
#  - ./gradlew clean build
#  - ./gradlew test
